### ISSUE TITLE
assignment #3 aside

### ISSUE THREAD

**Issue by andrewringler** [anitaviggh/web1-f16-student#1]
Anita,

Hi. Assignment #3 is looking great!

My only suggestion would be that your main navigation should probably not be in an aside. Typically aside means, something that is less important. Your main navigation is really important. I am not sure how screen-readers will treat this. I have to test.

If you take a look at http://alistapart.com/ they place their main nav, inside a nav, but not in any other container besides body, I am not sure why, but possibly this works well.

I have been placing my nav inside a header tag (http://massart.andrewringler.com/web1-f16/) but this is probably unnecessary if alistapart is not doing this. http://webaim.org/ also places their nav in a header which is why I have stuck to this method.

Andrew

**Comment by anitaviggh** [comment]
I didn't notice that, thanks. I'll change it to a header. I think that was a leftover quirk from when I was planning to put the title and navigation in a sidebar. I didn't realize screenreaders might handle that differently. Would aside be appropriate for sidebars in the future?
